// src/client/angular-client/src/app/demo.component.ts
import { Component, OnInit } from '@angular/core';
import { Apollo } from 'apollo-angular';

import gql from 'graphql-tag';

import { MyDetails } from './demo.types';

@Component({
  selector: 'app-demo',
  template: `
    <div style="text-align: center;">
      <p>Name: {{ myDetails.myName }}</p>
      <p>Address: {{ myDetails.myAddress }}</p>
    </div>
  `,
})
export class DemoComponent implements OnInit {
  myDetails: MyDetails;

  constructor(private apollo: Apollo) {}

  ngOnInit() {
    this.apollo
      .watchQuery<MyDetails>({
        query: gql`
          query {
            myName
            myAddress
          }
        `,
      })
      .valueChanges.subscribe(result => {
        this.myDetails = result.data;
      });
  }
}

// src/client/react-client/src/component/demo.js
import React from 'react';
import gql from 'graphql-tag';
import { Query } from 'react-apollo';

import MyDetails from './myDetails';

const GET_MY_DETAILS = gql`
  {
    myName
    myAddress
  }
`;

const Demo = () => (
  <Query query={GET_MY_DETAILS}>
    {result => {
      const { loading, error, data } = result;

      if (loading) {
        return <div>Loading</div>;
      }
      if (error) {
        return <div>Error</div>;
      }

      return <MyDetails data={data} />;
    }}
  </Query>
);

export default Demo;
